version: "3.3"
services:
  resources:
    build:
      context: ./src/Services/Resources.API
    ports:
      - "5000:80"
    environment:
      - "Endpoints:Redis=redis:6379"
    container_name: resources-api
    depends_on:
      - rabbitmq
      - redis
  redis:
    image: redis
    ports:
      - "32768:6379"
    container_name: redis
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 8080:15672
      - 5672:5672
    container_name: rabbitmq