version: "3.4"
services:
  resources:
    build:
      context: .
      dockerfile: ./src/Services/Resources.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - "Endpoints:Redis=redis:6379"
      - "Endpoints:RabbitMq=rabbitmq"
    container_name: resources-api
    depends_on:
      - rabbitmq
      - redis
  roster:
    build:
      context: .
      dockerfile: ./src/Services/Roster.API/Dockerfile
    ports:
      - "5001:80"
    environment:
      - "Endpoints:RabbitMq=rabbitmq"
    container_name: roster-api
    depends_on:
      - rabbitmq
  redis:
    image: redis
    ports:
      - "32768:6379"
    container_name: redis
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 8080:15672
      - 5672:5672
    container_name: rabbitmq