version: "3.3"
services:
  resources:
    build:
      context: ./src/Resources/Resources.API
    ports:
      - "5000:80"
    environment:
      - "Endpoints:Redis=http://redis-service:32768"
    container_name: resources-api
    depends_on:
      - redis-service
  redis-service:
    image: "redis"
    ports:
      - "32768:6379"
    container_name: redis