// <auto-generated />
using Microservices.Services.Revenue.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace Revenue.API.Migrations
{
    [DbContext(typeof(RevenueContext))]
    [Migration("20180224210430_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("Relational:Sequence:Revenue.TripSeq", "'TripSeq', 'Revenue', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microservices.Services.Revenue.Domain.AggregatesModel.TripAggregate.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:HiLoSequenceName", "TripSeq")
                        .HasAnnotation("SqlServer:HiLoSequenceSchema", "Revenue")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<Guid>("BusId");

                    b.Property<Guid>("ConductorId");

                    b.Property<Guid>("DriverId");

                    b.HasKey("Id");

                    b.ToTable("Trips","Revenue");
                });

            modelBuilder.Entity("Microservices.Services.Revenue.Domain.AggregatesModel.TripAggregate.Trip", b =>
                {
                    b.OwnsOne("System.Collections.Generic.List<Microservices.Services.Revenue.Domain.AggregatesModel.TripAggregate.TripLeg>", "TripLegs", b1 =>
                        {
                            b1.Property<int>("TripId");

                            b1.Property<int>("Capacity");

                            b1.ToTable("Trips","Revenue");

                            b1.HasOne("Microservices.Services.Revenue.Domain.AggregatesModel.TripAggregate.Trip")
                                .WithOne("TripLegs")
                                .HasForeignKey("System.Collections.Generic.List<Microservices.Services.Revenue.Domain.AggregatesModel.TripAggregate.TripLeg>", "TripId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
