apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservices
    component: sqlserver  
  name: sqlserver
spec:
  type: NodePort
  ports:
  - port: 1433
  selector:
    app: microservices
    component: sqlserver
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sqlserver
spec:
  template:
    metadata:
        labels:
          app: microservices
          component: sqlserver  
    spec:
      containers:
      - name: sqlserver
        image: microsoft/mssql-server-linux:2017-latest
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_PID
          value: Developer
        - name: MSSQL_SA_PASSWORD
          value: Pass_w0rd